export const GET_COUNTRY_LIST = 'GET_COUNTRY_LIST';
export const GET_SPECIFIC_COUNTRY = 'GET_SPECIFIC_COUNTRY';
export const GET_HISTORICAL_DATA_BY_COUNTRY = 'GET_HISTORICAL_DATA_BY_COUNTRY';
export const GET_HISTORICAL_GLOBAL = 'GET_HISTORICAL_GLOBAL';
export const SET_LOADING = 'SET_LOADING';
